#!/usr/bin/env node

import { execSync } from 'child_process';
import { readFileSync, writeFileSync, copyFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(query) {
  return new Promise((resolve) => rl.question(query, resolve));
}

function exec(command, options = {}) {
  console.log(`\n🔧 Running: ${command}`);
  try {
    execSync(command, { stdio: 'inherit', cwd: projectRoot, ...options });
  } catch (error) {
    console.error(`❌ Command failed: ${command}`);
    throw error;
  }
}

function copyTemplate(framework, filename, destination = filename) {
  const templatePath = join(projectRoot, 'templates', framework, filename);
  const destPath = join(projectRoot, destination);
  
  if (existsSync(templatePath)) {
    const destDir = dirname(destPath);
    if (!existsSync(destDir)) {
      mkdirSync(destDir, { recursive: true });
    }
    copyFileSync(templatePath, destPath);
    console.log(`✅ Created ${destination}`);
  } else {
    console.warn(`⚠️  Template not found: ${templatePath}`);
  }
}


async function scaffoldNextJS() {
  console.log('\n🚀 Scaffolding Next.js project...\n');
  
  // 1. Install dependencies
  console.log('📦 Installing dependencies...');
  exec('npm install next@latest react@latest react-dom@latest');
  
  console.log('📦 Installing dev dependencies...');
  exec('npm install -D typescript @types/node @types/react @types/react-dom postcss autoprefixer tailwindcss @tailwindcss/postcss eslint eslint-config-next');

  // 2. Create configuration files
  console.log('⚙️ Creating configuration files...');
  
  // next.config.ts
  const nextConfig = `
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
};

export default nextConfig;
`;
  writeFileSync(join(projectRoot, 'next.config.ts'), nextConfig.trim());

  // tailwind.config.ts
  const tailwindConfig = `
import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  plugins: [],
} satisfies Config;
`;
  writeFileSync(join(projectRoot, 'tailwind.config.ts'), tailwindConfig.trim());

  // postcss.config.mjs
  const postcssConfig = `
/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    '@tailwindcss/postcss': {},
    autoprefixer: {},
  },
};

export default config;
`;
  writeFileSync(join(projectRoot, 'postcss.config.mjs'), postcssConfig.trim());

  // tsconfig.json
  const tsConfig = `
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;
  writeFileSync(join(projectRoot, 'tsconfig.json'), tsConfig.trim());

  // .eslintrc.json
  const eslintConfig = `
{
  "extends": ["next/core-web-vitals", "next/typescript"]
}
`;
  writeFileSync(join(projectRoot, '.eslintrc.json'), eslintConfig.trim());

  // 3. Create structure
  console.log('📂 Creating project structure...');
  const appDir = join(projectRoot, 'app');
  if (!existsSync(appDir)) mkdirSync(appDir, { recursive: true });

  // app/globals.css
  const globalsCss = `
@import "tailwindcss";

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: Arial, Helvetica, sans-serif;
}
`;
  writeFileSync(join(appDir, 'globals.css'), globalsCss.trim());

  // app/layout.tsx
  const layoutTsx = `
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
`;
  writeFileSync(join(appDir, 'layout.tsx'), layoutTsx.trim());

  // app/page.tsx
  const pageTsx = `
import Image from "next/image";

export default function Home() {
  return (
    <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
      <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
        <h1 className="text-4xl font-bold">Welcome to Next.js</h1>
        <p className="text-lg">Get started by editing <code>app/page.tsx</code></p>
      </main>
    </div>
  );
}
`;
  writeFileSync(join(appDir, 'page.tsx'), pageTsx.trim());

  // Copy Next.js specific templates (retained from original)
  copyTemplate('nextjs', 'cursor-rules.mdc', '.cursor/rules/10-nextjs.mdc');
  copyTemplate('nextjs', 'CLAUDE.md', 'CLAUDE.md');
  copyTemplate('nextjs', 'docker-compose.yml', 'docker-compose.yml');
  copyTemplate('nextjs', 'Dockerfile', 'Dockerfile');
  copyTemplate('nextjs', '.dockerignore', '.dockerignore');
  
  // Update package.json scripts
  const packageJsonPath = join(projectRoot, 'package.json');
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
  
  packageJson.scripts = {
    ...packageJson.scripts,
    'dev': 'next dev',
    'build': 'next build',
    'start': 'next start',
    'lint': 'next lint',
    'docker:dev': 'docker-compose up',
    'docker:build': 'docker-compose build',
  };
  
  // Ensure "type": "module" does not conflict or is handled if needed
  // Next.js handles esm/commonjs effectively but manual scaffold might need attention if we rely on specific type settings.
  // The User's template package.json has "type": "module".
  
  writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2));
  console.log('✅ Updated package.json scripts');
  
  console.log('\n✨ Next.js scaffolding complete!');
  console.log('\n📝 Next steps:');
  console.log('   1. Run: npm run dev');
  console.log('   2. Review CLAUDE.md for architecture guidance');
}


async function scaffoldReactNative() {
  console.log('\n🚀 Scaffolding React Native project...\n');
  
  // Initialize React Native with Expo
  exec('npx create-expo-app@latest . --template blank-typescript --no-install');
  
  // Copy React Native specific templates
  copyTemplate('react-native', 'cursor-rules.mdc', '.cursor/rules/10-react-native.mdc');
  copyTemplate('react-native', 'CLAUDE.md', 'CLAUDE.md');
  
  // Update package.json scripts
  const packageJsonPath = join(projectRoot, 'package.json');
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
  
  packageJson.scripts = {
    ...packageJson.scripts,
    'start': 'expo start',
    'android': 'expo start --android',
    'ios': 'expo start --ios',
    'web': 'expo start --web',
  };
  
  writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2));
  console.log('✅ Updated package.json scripts');
  
  console.log('\n✨ React Native scaffolding complete!');
  console.log('\n📝 Next steps:');
  console.log('   1. Run: npm install');
  console.log('   2. Run: npm start');
  console.log('   3. Review CLAUDE.md for architecture guidance');
}

async function main() {
  console.log('🎨 AI POC Template - Framework Scaffolding\n');
  console.log('This will initialize a framework in the current directory.');
  console.log('⚠️  Warning: This will modify package.json and add new files.\n');
  
  const framework = await question('Choose framework (1 = Next.js, 2 = React Native): ');
  
  if (framework === '1') {
    await scaffoldNextJS();
  } else if (framework === '2') {
    await scaffoldReactNative();
  } else {
    console.log('❌ Invalid choice. Please run again and choose 1 or 2.');
    process.exit(1);
  }
  
  rl.close();
}

main().catch((error) => {
  console.error('\n❌ Scaffolding failed:', error.message);
  process.exit(1);
});
